[package]
name = "animal_chess"
version = "0.1.0"
authors = ["netcan <1469709759@qq.com>"]
edition = "2018"

[dependencies]
array-macro = "1.0.5"

[dependencies.sdl2]
version = "0.34.0"
default-features = false
features = ["image", "unsafe_textures"]

